# Generated by Django 3.0.7 on 2020-06-06 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=200, verbose_name='Database Name')),
                ('db_user', models.CharField(max_length=200, verbose_name='Database User')),
                ('db_password', models.CharField(max_length=200, verbose_name='Database Password')),
                ('host', models.CharField(max_length=200, verbose_name='Host')),
                ('port', models.IntegerField(default=0, verbose_name='Port')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'DB Instance',
                'verbose_name_plural': 'DB Instances',
            },
        ),
    ]
