# Generated by Django 3.0.7 on 2020-06-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metamorphic', '0002_auto_20200609_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=200, verbose_name='Query ID')),
                ('query_text', models.CharField(max_length=1000, verbose_name='Query')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamorphic.DBInstance')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
            },
        ),
    ]
