# Generated by Django 3.0.7 on 2020-06-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamorphic', '0004_query_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_id',
            field=models.CharField(max_length=200, unique='True', verbose_name='Query ID'),
        ),
    ]
