# Generated by Django 3.0.7 on 2020-08-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamorphic', '0005_auto_20200609_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='user',
        ),
    ]
